# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This is a script which converts the md files into usable files (to be run before jekyll build)

# Grab existing files
READMECONTENTS=`cat README.md`
LICENSECONTENTS=`cat LICENSE`

# Make README.md into default index (/)
cat >./index.md  <<EOF
---
layout: default
permalink: /
---

${READMECONTENTS}
EOF

# Make LICENSE.md into /license/
cat >./LICENSE.md <<EOF
---
layout: default
permalink: /license/
---

# License

${LICENSECONTENTS}
EOF
